# Generated by Django 5.2.4 on 2025-07-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата синхронизации"
                    ),
                ),
                (
                    "new_count",
                    models.PositiveIntegerField(
                        verbose_name="Количество новых ивентов"
                    ),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(
                        verbose_name="Количество обновленных ивентов"
                    ),
                ),
            ],
        ),
    ]
