# Generated by Django 5.2.4 on 2025-07-28 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventPlaceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название места проведения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID мероприятия",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(verbose_name="Дата проведения мероприятия"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыто"), ("closed", "Закрыто")],
                        max_length=6,
                        verbose_name="Статус мероприятия",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.eventplacemodel",
                        verbose_name="Место проведения мероприятия",
                    ),
                ),
            ],
        ),
    ]
