# Generated by Django 5.2.4 on 2025-07-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventmodel",
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="eventplacemodel",
            options={
                "verbose_name": "Место проведения мероприятия",
                "verbose_name_plural": "Места проведения мероприятий",
            },
        ),
    ]
