# Generated by Django 5.2.4 on 2025-07-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_eventmodel_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventmodel",
            old_name="date",
            new_name="event_time",
        ),
        migrations.RenameField(
            model_name="eventmodel",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="eventplacemodel",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="registration_deadline",
            field=models.DateTimeField(
                default="2025-01-01", verbose_name="Дата окончания регистрации"
            ),
            preserve_default=False,
        ),
    ]
